question_data = [
    {"text": "A slug's blood is green", "answer": "True"},
    {"text": "The loudest animal is the African Elephant", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to "
             "eat", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs", "answer": "False"},
    {"text": "Google was originally called 'Backrub'", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog", "answer": "True"},
    {"text": "Marrakesh is the capital of Morocco", "answer": "False"},
    {"text": "Idina Menzel sings 'let it go' 20 times in 'Let It Go' from Frozen", "answer": "False"},
    {"text": "M&M stands for Mars and Moordale", "answer": "False"},
    {"text": "The unicorn is the national animal of Scotland", "answer": "True"},
    {"text": "There are two parts of the body that can't heal themselves", "answer": "False"},
    {"text": "The Great Wall of China is longer than the distance between London and Beijing", "answer": "True"},
    {"text": "'A' is the most common letter used in the English language", "answer": "False"},
    {"text": "A lion's roar can be heard up to eight kilometres away", "answer": "True"},
    {"text": "In Harry Potter, Draco Malfoy has no siblings", "answer": "False"},
    {"text": "There are five different blood groups", "answer": "False"},
    {"text": "H&M stands for Hennes & Mauritz", "answer": "True"},
    {"text": "Canis lupur is the scientific name for a wolf", "answer": "False"},
    {"text": "Coffee is made from berries", "answer": "True"},
    {"text": "The only letter not in the periodic table is the letter J", "answer": "True"},
    {"text": "The small intestine is about three-and-a-half times the length of your body", "answer": "True"},
    {"text": "An octopus has three hearts", "answer": "True"},
    {"text": "Thomas Edison discovered gravity", "answer": "False"},
    {"text": "Spaghetto is the singular word for a piece of spaghetti", "answer": "True"},
    {"text": "Bananas are curved because they grow upwards towards the sun", "answer": "True"},
    {"text": "The five rings on the Olympic flag are interlocking", "answer": "True"},
    {"text": "Mount Kilimanjaro is the highest mountain in the world", "answer": ""},
    {"text": "A group of swans is known as a bevy", "answer": "True"},
    {"text": "Sydney is the capital of Australia", "answer": "False"},
    {"text": "A heptagon has eight sides", "answer": "False"},
    {"text": "Fish cannot blink", "answer": "True"},
    {"text": "Seahorses have no teeth or stomach", "answer": "True"},
]
